#!/usr/bin/env python3
"""Export the workbook's Definitions sheet to definitions.json, pruned to terms in use.

The app's Definitions page used to be a hardcoded dict, which is why it drifted: it
had no Event type or Sub-type section at all, and defined a `Confidence` term the
tracker does not have. Maintaining a second copy by hand recreates that drift on the
next edit, so the app reads this file instead and the workbook stays the single source
of truth.

The file is committed rather than read from the workbook at runtime for two reasons:
the CSV-only deploy path has no workbook to read, and a JSON file that ships with the
app cannot fail to load. `validate.py`'s `definitions_export` rule regenerates it in
memory and fails if what is committed has gone stale, so it cannot silently rot.

Pruned to terms in use, because a glossary listing categories nobody has ever logged
teaches the reader nothing:

  field definitions   kept when the tracker actually has that column
  value taxonomies    kept when some record carries that value
  operational terms   kept when the term appears in the tracker's own text

Usage:  python3 scripts/export_definitions.py [--check]
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent))
from validate import DEFAULT_CSV, DEFAULT_XLSX, definitions_entries  # noqa: E402

REPO = Path(__file__).resolve().parent.parent
DEFAULT_JSON = REPO / "definitions.json"

# Sheet section -> the heading the app shows, in the order the app shows them. A
# section absent here still exports, under its own name, at the end -- a new section
# on the sheet should appear in the app rather than vanish from it.
GROUPS = [
    ("Field definition", "Tracker fields"),
    ("Issue type", "Issue types"),
    ("Event type", "Event types"),
    ("Reason label", "Reason labels"),
    ("Root cause", "Root causes"),
    ("Sub-type", "Sub-types"),
    ("Severity", "Severity levels"),
    ("Fix status", "Fix statuses"),
    ("Improvement classification", "Improvement vs bug"),
    ("Boolean flag", "Flags"),
    ("Automation focus", "Automation focus"),
    ("Operational term", "Operational terms"),
]


def build(csv_path: Path = DEFAULT_CSV, xlsx_path: Path = DEFAULT_XLSX) -> dict:
    entries = definitions_entries(xlsx_path)
    if entries is None:
        raise SystemExit(f"{xlsx_path.name} has no Definitions sheet")
    df = pd.read_csv(csv_path, dtype=str, keep_default_na=False)

    used: dict[str, set[str]] = {
        col: {v.strip() for v in df[col] if str(v).strip()} for col in df.columns
    }
    # One lowercase haystack of every text cell, for the operational-term test.
    prose = " ".join(df[c].astype(str).str.cat(sep=" ") for c in df.columns).lower()

    def in_use(entry: dict) -> bool:
        section, term, source = entry["section"], entry["term"], entry["source"]
        if section == "Field definition":
            return source in df.columns
        if section == "Operational term":
            return re.search(rf"\b{re.escape(term.lower())}\b", prose) is not None
        if source not in used:
            return False
        # Boolean flags read "Yes -- Missed_Flag" so the sheet can define both senses
        # of a shared word; match on the value, not the disambiguated label.
        value = re.sub(rf"\s+[—-]\s+{re.escape(source)}$", "", term).strip()
        return value in used[source]

    kept = [e for e in entries if e["term"] and in_use(e)]
    order = {section: i for i, (section, _) in enumerate(GROUPS)}
    titles = dict(GROUPS)

    groups = []
    for section in sorted({e["section"] for e in kept},
                          key=lambda s: (order.get(s, len(order)), s)):
        rows = [[e["term"], e["definition"], e["allowed"]]
                for e in kept if e["section"] == section]
        groups.append({"section": section, "title": titles.get(section, section), "rows": rows})

    return {
        "_comment": "Generated by scripts/export_definitions.py from the workbook's "
                    "Definitions sheet, pruned to terms in use. Do not edit by hand; "
                    "edit the sheet and re-run. validate.py fails if this goes stale.",
        "source": xlsx_path.name,
        "terms": sum(len(g["rows"]) for g in groups),
        "pruned": len([e for e in entries if e["term"]]) - len(kept),
        "groups": groups,
    }


def render(payload: dict) -> str:
    return json.dumps(payload, indent=2, ensure_ascii=False) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--csv", type=Path, default=DEFAULT_CSV)
    ap.add_argument("--xlsx", type=Path, default=DEFAULT_XLSX)
    ap.add_argument("--out", type=Path, default=DEFAULT_JSON)
    ap.add_argument("--check", action="store_true", help="exit non-zero if the file is stale")
    args = ap.parse_args()

    payload = build(args.csv, args.xlsx)
    text = render(payload)
    current = args.out.read_text(encoding="utf-8") if args.out.exists() else None
    if args.check:
        if current == text:
            print(f"{args.out.name} is current: {payload['terms']} terms in "
                  f"{len(payload['groups'])} groups ({payload['pruned']} pruned as unused)")
            return 0
        print(f"{args.out.name} is stale; run `python3 scripts/export_definitions.py`")
        return 1
    if current == text:
        print(f"{args.out.name} already current ({payload['terms']} terms)")
        return 0
    args.out.write_text(text, encoding="utf-8")
    print(f"wrote {args.out.name}: {payload['terms']} terms in {len(payload['groups'])} groups "
          f"({payload['pruned']} pruned as unused)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
